version: "3"

services:
  clash:
    restart: always
    build: .
    environment:
      - TZ=Asia/Shanghai
      - sub=
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: 1m
